### ISSUE TITLE
Intention of this project?

### ISSUE THREAD

**Issue by Boscop** [rosarp/llm-lsp#1]
Hey, I found this crate because I'm working on a similar project (combining LLMs with LSP).
It seems like you abandoned this project but I'm very curious, what was your original intention with this project? :)

**Comment by rosarp** [comment]
Hi @Boscop , I didn't get time to work on it for a while. Intention is to have LSP interface for LLMs such as local LLM model or codeium or any other. So that any editor can use this binary as lsp server which will get code completions from LLMs. 

I will mostly start again on this soon.

**Comment by rosarp** [comment]
I have started with codeium integration. Closing this issue.
